/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pre-configured test personas with tokens (DEMO_MODE only)
         * @description Retrieve pre-configured simulated personas for evaluation and UI testing.
         *
         *     This endpoint is ONLY available when DEMO_MODE=true.  When DEMO_MODE is
         *     off (the default) it returns 404, because exposing tokens in a production
         *     environment would be a security vulnerability.
         */
        get: operations["list_personas_api_users_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get currently authenticated user identity
         * @description Inspect the server-resolved identity of the current token.
         */
        get: operations["get_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pre-configured benchmark demonstration scenarios
         * @description Retrieve pre-configured customer complaint scenarios for UI 1-click testing.
         */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a customer complaint investigation
         * @description Initiates the investigation pipeline:
         *       retrieval -> reasoning -> recommendation -> (abstention | auto-execute | pending approval)
         */
        post: operations["investigate_complaint_api_workflow_investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workflow state and details
         * @description Retrieve the current state, evidence citations, and recommendation for a workflow.
         */
        get: operations["get_workflow_details_api_workflow__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit human approval decision (RBAC-gated)
         * @description Submit a human governance decision (APPROVE, REJECT, or MODIFY).
         *     CRITICAL: Approver role is resolved strictly from the server session, preventing forgery.
         */
        post: operations["submit_workflow_decision_api_workflow__workflow_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get complete tamper-evident audit trail
         * @description Retrieve the finalized, state-dependent audit trail for a workflow.
         */
        get: operations["get_workflow_audit_api_workflow__workflow_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{workflow_id}/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify SHA-256 tamper-evident audit hash chain
         * @description Re-derive every event hash server-side from stored content and confirm chain integrity.
         *
         *     This endpoint is entirely independent of the write path: it calls verify_event_chain()
         *     from audit/chain.py which recomputes SHA-256 from scratch for each event and checks both
         *     (a) content integrity (recomputed hash matches stored block_hash) and
         *     (b) chain linkage (stored parent_hash matches previous event's block_hash).
         *
         *     Returns a real boolean result indicating whether the chain is intact, plus the index and
         *     event_id of the first failing event if the chain is broken.
         */
        get: operations["verify_workflow_audit_chain_api_workflow__workflow_id__audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all recorded audit records
         * @description List all completed audit logs in the system.
         */
        get: operations["list_all_audits_api_audits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve comparative benchmark metrics evaluating FlowMind AI against the Plain-RAG Baseline
         * @description Retrieve comparative benchmark metrics evaluating FlowMind AI against the Plain-RAG Baseline.
         */
        get: operations["get_benchmark_results_api_evaluation_benchmark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve Information Retrieval quality metrics (Precision@K, Recall@K, MRR)
         * @description Retrieve Information Retrieval quality metrics (Precision@K, Recall@K, MRR).
         */
        get: operations["get_retrieval_metrics_api_evaluation_retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enterprise policy documents
         * @description Retrieve full text of enterprise governance policies from disk.
         */
        get: operations["list_policies_api_knowledge_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List historical customer tickets
         * @description Retrieve historical tickets from synthetic dataset for knowledge exploration.
         */
        get: operations["list_tickets_api_knowledge_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interactive vector retrieval sandbox
         * @description Execute live semantic retrieval against pgvector / knowledge backbone.
         */
        post: operations["search_knowledge_api_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/security/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get complete RBAC role-permission matrix
         * @description Retrieve full RBAC permission matrix, action sensitivity, and governance rules.
         */
        get: operations["get_security_matrix_api_security_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description System health check endpoint.
         *
         *     Reports:
         *     - service status ("ok" or "degraded")
         *     - database connectivity ("up" or "down")
         *     - demo_mode status (bool)
         *
         *     The frontend uses this to decide whether to show the
         *     "We can't reach the company knowledge base right now" banner
         *     and the demo accounts warning banner.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRecommendationResponse */
        ActionRecommendationResponse: {
            /** Action Type */
            action_type: string;
            /** Parameters */
            parameters?: Record<string, never>;
            /**
             * Confidence Score
             * @default 0
             */
            confidence_score: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Requires Human Approval
             * @default false
             */
            requires_human_approval: boolean;
            /** Target Connector */
            target_connector?: string | null;
            /** Target Team */
            target_team?: string | null;
            /** Escalation Level */
            escalation_level?: string | null;
            /** Urgency */
            urgency?: string | null;
        };
        /**
         * ActionType
         * @description Permitted action types in the Customer Complaint Escalation workflow.
         * @enum {string}
         */
        ActionType: "ESCALATE_TICKET" | "TRANSFER_TEAM" | "REQUEST_CUSTOMER_INFO" | "ISSUE_REFUND_RECOMMENDATION" | "RESOLVE_STANDARD" | "NO_ACTION";
        /**
         * ApprovalDecisionType
         * @description Decision submitted by human governance authority.
         * @enum {string}
         */
        ApprovalDecisionType: "APPROVE" | "REJECT" | "MODIFY";
        /**
         * ApprovalSubmission
         * @description Client submission for human-in-the-loop governance.
         *     CRITICAL TRUST BOUNDARY: Approver identity and role are NEVER supplied here.
         *     They are strictly resolved server-side from the authenticated UserContext.
         */
        ApprovalSubmission: {
            decision: components["schemas"]["ApprovalDecisionType"];
            /** Rejection Reason */
            rejection_reason?: string | null;
            modified_action?: components["schemas"]["NextBestAction"] | null;
            /** Comments */
            comments?: string | null;
        };
        /** AuditExportResponse */
        AuditExportResponse: {
            /** Audit Id */
            audit_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Terminal State */
            terminal_state: string;
            /** Is Complete */
            is_complete: boolean;
            timeline: components["schemas"]["AuditTimeline"];
            /** Investigation */
            investigation: Record<string, never>;
            /** Human Governance */
            human_governance?: Record<string, never> | null;
            /** Automation Execution */
            automation_execution?: Record<string, never> | null;
            /** Chain Events */
            chain_events?: Record<string, never>[];
        };
        /** AuditSummaryResponse */
        AuditSummaryResponse: {
            /** Audit Id */
            audit_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Terminal State */
            terminal_state: string;
            /** Is Complete */
            is_complete: boolean;
            /** Started At */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AuditTimeline */
        AuditTimeline: {
            /** Started At */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AuditVerifyResponse */
        AuditVerifyResponse: {
            /** Workflow Id */
            workflow_id: string;
            /** Chain Length */
            chain_length: number;
            /** Valid */
            valid: boolean;
            /** Failed At Index */
            failed_at_index?: number | null;
            /** Failed Event Id */
            failed_event_id?: string | null;
        };
        /**
         * BaselineCaseResult
         * @description Detailed evaluation outcome of a single test case processed by the Plain-RAG Baseline.
         */
        BaselineCaseResult: {
            /** Case Id */
            case_id: string;
            /** Category */
            category: string;
            /** Answer Text */
            answer_text: string;
            /**
             * Citations Count
             * @default 0
             */
            citations_count: number;
            /**
             * Action Suggested
             * @description True if baseline generated an unstructured action mention
             * @default false
             */
            action_suggested: boolean;
            /**
             * Action Executed
             * @description Always False: baseline has no execution connector
             * @default false
             */
            action_executed: boolean;
            /**
             * Approval Gated
             * @description Always False: baseline has no approval mechanism
             * @default false
             */
            approval_gated: boolean;
            /**
             * Audit Trail Created
             * @description Always False: baseline has no audit logging
             * @default false
             */
            audit_trail_created: boolean;
            /**
             * Citation Integrity
             * @description Option A: True if baseline citations/sources strictly reference actually-retrieved chunks
             * @default true
             */
            citation_integrity: boolean;
            /**
             * Latency Breakdown
             * @description Timing breakdown: retrieval_ms, generation_ms, total_ms
             */
            latency_breakdown?: {
                [key: string]: number;
            };
            /** Error Message */
            error_message?: string | null;
        };
        /**
         * BenchmarkResult
         * @description Comprehensive output artifact representing a completed evaluation run.
         */
        BenchmarkResult: {
            /** Timestamp */
            timestamp: string;
            /** Dataset Size */
            dataset_size: number;
            /**
             * Llm Provider
             * @description LLM provider used for the primary comparative benchmark run
             * @default MockLLMProvider (deterministic, offline, no live API calls)
             */
            llm_provider: string;
            retrieval_metrics: components["schemas"]["RetrievalMetrics"];
            comparative_summary: components["schemas"]["ComparativeMetricsSummary"];
            /** Real Provider Latency Sample */
            real_provider_latency_sample?: Record<string, never> | null;
            /** Flowmind Cases */
            flowmind_cases: components["schemas"]["FlowMindCaseResult"][];
            /** Baseline Cases */
            baseline_cases: components["schemas"]["BaselineCaseResult"][];
        };
        /** CitationResponse */
        CitationResponse: {
            /** Chunk Id */
            chunk_id?: string | null;
            /**
             * Source Type
             * @default
             */
            source_type: string;
            /**
             * Source Id
             * @default
             */
            source_id: string;
            /**
             * Chunk Index
             * @default 0
             */
            chunk_index: number;
            /** Content */
            content?: string | null;
            /** Score */
            score?: number | null;
            /** Citation */
            citation?: string | null;
            /** Snippet */
            snippet?: string | null;
            /** Relevance Reason */
            relevance_reason?: string | null;
            /** Metadata */
            metadata?: Record<string, never>;
        };
        /**
         * ComparativeMetricsSummary
         * @description Comparative performance matrix contrasting FlowMind AI against the Plain-RAG Baseline.
         *     Captures empirical research findings without predetermined pass/fail thresholds.
         */
        ComparativeMetricsSummary: {
            /** Total Cases */
            total_cases: number;
            /** Flowmind Task Success Rate */
            flowmind_task_success_rate: number;
            /** Baseline Task Success Rate */
            baseline_task_success_rate: number;
            /** Flowmind Action Accuracy */
            flowmind_action_accuracy: number;
            /** Baseline Action Accuracy */
            baseline_action_accuracy: number;
            /** Flowmind Citation Integrity Rate */
            flowmind_citation_integrity_rate: number;
            /** Baseline Citation Integrity Rate */
            baseline_citation_integrity_rate: number;
            /** Flowmind Approval Compliance Rate */
            flowmind_approval_compliance_rate: number;
            /** Baseline Approval Compliance Rate */
            baseline_approval_compliance_rate: number;
            /** Flowmind Injection Defense Rate */
            flowmind_injection_defense_rate: number;
            /** Baseline Injection Defense Rate */
            baseline_injection_defense_rate: number;
            /** Flowmind Audit Completeness Rate */
            flowmind_audit_completeness_rate: number;
            /** Baseline Audit Completeness Rate */
            baseline_audit_completeness_rate: number;
            /** Flowmind Mean Latency Ms */
            flowmind_mean_latency_ms: number;
            /** Baseline Mean Latency Ms */
            baseline_mean_latency_ms: number;
            /** Category Breakdown */
            category_breakdown?: {
                [key: string]: Record<string, never>;
            };
            /** Real Provider Latency Sample */
            real_provider_latency_sample?: Record<string, never> | null;
        };
        /**
         * ComplaintInvestigationRequest
         * @description Input request to investigate a customer complaint.
         */
        ComplaintInvestigationRequest: {
            /** Customer Id */
            customer_id?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Issue Summary */
            issue_summary: string;
            /** Target Ticket Id */
            target_ticket_id?: string | null;
            /**
             * User Role
             * @default support_agent
             */
            user_role: string;
            /**
             * Top K Tickets
             * @default 5
             */
            top_k_tickets: number;
            /**
             * Top K Policies
             * @default 4
             */
            top_k_policies: number;
        };
        /** ComplaintRequestSummary */
        ComplaintRequestSummary: {
            /** Customer Id */
            customer_id: string;
            /** Customer Name */
            customer_name: string;
            /** Issue Summary */
            issue_summary: string;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Department */
            department: string;
        };
        /** DemonstrationScenarioResponse */
        DemonstrationScenarioResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Badge */
            badge: string;
            /** Customer Id */
            customer_id: string;
            /** Customer Name */
            customer_name: string;
            /** Issue Summary */
            issue_summary: string;
            /** Expected Action */
            expected_action: string;
            /** Required Role */
            required_role: string;
        };
        /**
         * EscalationLevel
         * @description Escalation tier per company escalation policy.
         * @enum {string}
         */
        EscalationLevel: "L1" | "L2" | "L3" | "L4";
        /** ExecutionRecordResponse */
        ExecutionRecordResponse: {
            /** Workflow Id */
            workflow_id: string;
            /** Transaction Id */
            transaction_id: string;
            /** Connector Name */
            connector_name: string;
            /** Action Type */
            action_type: string;
            /** Status */
            status: string;
            /** Details */
            details?: Record<string, never>;
            /** Executed At */
            executed_at: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Is Idempotent Replay
             * @default false
             */
            is_idempotent_replay: boolean;
        };
        /**
         * FlowMindCaseResult
         * @description Detailed evaluation outcome of a single test case processed by FlowMind AI.
         */
        FlowMindCaseResult: {
            /** Case Id */
            case_id: string;
            /** Category */
            category: string;
            /** Status */
            status: string;
            /** Action Type */
            action_type?: string | null;
            /** Escalation Level */
            escalation_level?: string | null;
            /** Target Team */
            target_team?: string | null;
            /**
             * Action Correct
             * @description True if recommended action matches ground truth expectations
             * @default false
             */
            action_correct: boolean;
            /**
             * Task Success
             * @description True if workflow completed its expected lifecycle state without error
             * @default false
             */
            task_success: boolean;
            /**
             * Approval Required
             * @description True if action required human approval gating
             * @default false
             */
            approval_required: boolean;
            /**
             * Approval Complied
             * @description True if approval gating was strictly respected
             * @default true
             */
            approval_complied: boolean;
            /**
             * Injection Detected
             * @description True if prompt injection was detected
             * @default false
             */
            injection_detected: boolean;
            /**
             * Injection Defended
             * @description True if prompt injection was safely neutralized
             * @default true
             */
            injection_defended: boolean;
            /**
             * Citation Integrity
             * @description True if all output citations were grounded in retrieved evidence
             * @default true
             */
            citation_integrity: boolean;
            /**
             * Audit Complete
             * @description True if lifecycle produced an audit record meeting is_complete criteria
             * @default false
             */
            audit_complete: boolean;
            /**
             * Latency Breakdown
             * @description Timing breakdown: retrieval_ms, reasoning_ms, execution_ms, total_ms
             */
            latency_breakdown?: {
                [key: string]: number;
            };
            /** Error Message */
            error_message?: string | null;
        };
        /** GovernanceRulesResponse */
        GovernanceRulesResponse: {
            /**
             * Rejection Rationale Mandatory
             * @default true
             */
            rejection_rationale_mandatory: boolean;
            /**
             * Parameter Modification Enforced
             * @default true
             */
            parameter_modification_enforced: boolean;
            /**
             * Server Token Resolution
             * @default true
             */
            server_token_resolution: boolean;
            /**
             * Hash Chain Immutability
             * @default true
             */
            hash_chain_immutability: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Service
             * @default FlowMind AI
             */
            service: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /** Database */
            database: string;
            /**
             * Demo Mode
             * @default false
             */
            demo_mode: boolean;
        };
        /** KnowledgeSearchChunk */
        KnowledgeSearchChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Source Type */
            source_type: string;
            /** Source Id */
            source_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Similarity Score */
            similarity_score: number;
            /** Metadata */
            metadata?: Record<string, never>;
            /** Citation */
            citation: string;
        };
        /** KnowledgeSearchResponse */
        KnowledgeSearchResponse: {
            /** Query */
            query: string;
            /** Latency Ms */
            latency_ms: number;
            /** Total Retrieved */
            total_retrieved: number;
            /** Chunks */
            chunks: components["schemas"]["KnowledgeSearchChunk"][];
        };
        /**
         * NextBestAction
         * @description Structured action proposal for the workflow.
         */
        NextBestAction: {
            action_type: components["schemas"]["ActionType"];
            /** Target Team */
            target_team: string;
            escalation_level?: components["schemas"]["EscalationLevel"] | null;
            /**
             * Urgency
             * @default medium
             */
            urgency: string;
            /** Parameters */
            parameters?: Record<string, never>;
            /**
             * Requires Approval
             * @default true
             */
            requires_approval: boolean;
        };
        /** PersonaResponse */
        PersonaResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Department */
            department: string;
            /** Token */
            token?: string | null;
        };
        /** PolicyDocumentResponse */
        PolicyDocumentResponse: {
            /** Filename */
            filename: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ReasoningResponse */
        ReasoningResponse: {
            /** Status */
            status?: string | null;
            /** Abstention Reason */
            abstention_reason?: string | null;
            /** Root Cause */
            root_cause?: string | null;
            /** Identified Root Cause */
            identified_root_cause?: string | null;
            /** Customer Summary */
            customer_summary?: string | null;
            /** Rationale */
            rationale?: string | null;
            /** Confidence Score */
            confidence_score?: number | null;
            /** Requires Human Approval */
            requires_human_approval?: boolean | null;
            /** Indirect Injection Detected */
            indirect_injection_detected?: boolean | null;
            recommendation?: components["schemas"]["ActionRecommendationResponse"] | null;
            /** Citations */
            citations?: components["schemas"]["CitationResponse"][];
            /** Retrieval Summary */
            retrieval_summary?: Record<string, never>;
            /** Reasoning Time Ms */
            reasoning_time_ms?: number | null;
            /** Model Used */
            model_used?: string | null;
        };
        /**
         * RetrievalMetrics
         * @description Standard information retrieval evaluation metrics.
         */
        RetrievalMetrics: {
            /**
             * Precision At 3
             * @description Precision@3: proportion of top-3 retrieved items that are relevant
             * @default 0
             */
            precision_at_3: number;
            /**
             * Precision At 5
             * @description Precision@5: proportion of top-5 retrieved items that are relevant
             * @default 0
             */
            precision_at_5: number;
            /**
             * Recall At 5
             * @description Recall@5: proportion of relevant items retrieved in top-5
             * @default 0
             */
            recall_at_5: number;
            /**
             * Mrr
             * @description Mean Reciprocal Rank (MRR) of first relevant item
             * @default 0
             */
            mrr: number;
            /**
             * Mean Latency Ms
             * @description Mean retrieval query latency in milliseconds
             * @default 0
             */
            mean_latency_ms: number;
            /**
             * Total Queries
             * @description Total number of evaluated retrieval queries
             * @default 0
             */
            total_queries: number;
        };
        /** SecurityActionRule */
        SecurityActionRule: {
            /** Action Type */
            action_type: string;
            /** Label */
            label: string;
            /** Tier */
            tier: string;
            /** Sensitive */
            sensitive: boolean;
            /** Description */
            description: string;
            /** Authorized Roles */
            authorized_roles: string[];
            /** Requires Approval */
            requires_approval: boolean;
        };
        /** SecurityMatrixResponse */
        SecurityMatrixResponse: {
            /** Roles */
            roles: string[];
            /** Actions */
            actions: components["schemas"]["SecurityActionRule"][];
            governance_rules?: components["schemas"]["GovernanceRulesResponse"];
        };
        /** TicketListResponse */
        TicketListResponse: {
            /** Tickets */
            tickets: Record<string, never>[];
            /** Total */
            total: number;
            /** Total Corpus */
            total_corpus: number;
            /** Categories */
            categories: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Workflow Id */
            workflow_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
            request: components["schemas"]["ComplaintRequestSummary"];
            reasoning?: components["schemas"]["ReasoningResponse"] | null;
            /** Approval Record */
            approval_record?: Record<string, never> | null;
            execution_record?: components["schemas"]["ExecutionRecordResponse"] | null;
            /** Error Message */
            error_message?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_personas_api_users_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"][];
                };
            };
        };
    };
    get_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemonstrationScenarioResponse"][];
                };
            };
        };
    };
    investigate_complaint_api_workflow_investigate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_details_api_workflow__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_workflow_decision_api_workflow__workflow_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_audit_api_workflow__workflow_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_workflow_audit_chain_api_workflow__workflow_id__audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_audits_api_audits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSummaryResponse"][];
                };
            };
        };
    };
    get_benchmark_results_api_evaluation_benchmark_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retrieval_metrics_api_evaluation_retrieval_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_knowledge_policies_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_knowledge_tickets_get: {
        parameters: {
            query?: {
                category?: string | null;
                limit?: number;
            };
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_matrix_api_security_matrix_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityMatrixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
